In [ ]:
import rev
# load a chart
chart = rev.Chart('examples/vega1.png', text_from=0)

In [ ]:
# training text role classifier
import pandas as pd
import rev.text
data = pd.read_csv('data/features_all.csv')
features = data[rev.text.classifier.VALID_COLUMNS]
types = data['type']

text_clf = rev.text.TextClassifier()
text_clf.train(features, types)

In [ ]:
##########################################################################################
# mark type classifier
import rev.mark
mark_clf = rev.mark.MarkClassifier()
print (mark_clf.classify([chart]))

In [ ]:
##########################################################################################
#feature extraction (single)
import rev.text
text_features = rev.text.feature_extractor.from_chart(chart)
print (text_features)

In [ ]:
##########################################################################################
# text role classification
import rev
# load a chart
chart = rev.Chart('examples/vega1.png', text_from=0)
import rev.text
text_clf = rev.text.TextClassifier('default')
text_type_preds = text_clf.classify(chart)
print (text_type_preds)
##########################################################################################

In [ ]:
# training text role classifier
import rev.text
import pandas as pd
data = pd.read_csv('data/features_all.csv')
features = data[rev.text.classifier.VALID_COLUMNS]
types = data['type']

text_clf = rev.text.TextClassifier()
text_clf.train(features, types)
text_clf.save_model('models/new_text_role_classifier/text_type_classifier.pkl')

In [ ]:
%load_ext autoreload
%autoreload 2

In [2]:
import rev
from rev.text.localizer import TextLocalizer

# load a chart
chart = rev.Chart('examples/vega1.png', text_from=0)
localizer = TextLocalizer()
text_boxes = localizer.localize(chart, method='default', debug = False)

new_chart = chart.copy(text_from=2)
new_chart.text_boxes = text_boxes
new_chart.save_text_boxes()
new_chart.save_debug_image()

[[0 7 0 ... 1 1 1]
 [4 0 6 ... 2 2 2]
 [0 0 4 ... 2 2 2]
 ...
 [0 5 0 ... 1 1 9]
 [5 2 0 ... 2 8 0]
 [3 0 2 ... 0 1 0]]
most common character height is:  19
most common edge length is:  14


In [1]:
import rev
from rev.text.localizer import TextLocalizer

# load a chart
chart = rev.Chart('examples/vega1.png', text_from=0)
localizer = TextLocalizer()
text_boxes = localizer.localize(chart, method='pixel_link', debug=False)
new_chart = chart.copy(text_from=2)
new_chart.text_boxes = text_boxes
new_chart.save_text_boxes()
new_chart.save_debug_image()

/home/joao/anaconda3/envs/reverse/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/joao/anaconda3/envs/reverse/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/joao/anaconda3/envs/reverse/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/joao/anaconda3/envs/reverse/lib/python3.6/s


Instructions for updating:
Please switch to tf.train.get_or_create_global_step


/home/joao/anaconda3/envs/reverse/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/joao/anaconda3/envs/reverse/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/joao/anaconda3/envs/reverse/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/joao/anaconda3/envs/re

Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
    
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /home/joao/Documents/repos/rev/rev/text/../../models/pixel_link_text_detection/model.ckpt-46231
